server:
  port: 8808
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.137.101:3306/test1
      username: root
      password: 1234
logging:
  level:
    com.example.test1.mapper: DEBUG #包路径为mapper文件包路径com.example.test1.mapper
